[package]
name = "rust-enroll"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = "2.0.13"
borsh = "0.10.3"
solana-idlgen = { git = "https://github.com/deanmlittle/solana-idlgen.git" }
solana-client = "2.0.13"
solana-program = "2.0.13"
bs58 = "0.5.1"